### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by sdspikes**
Work in progress. 

Tests now all build and run. 

Non-UI tests all pass, but many of the UI tests are currently failing on a timeout. Will look into why tomorrow.

### CODE REVIEW

**Comment by zestyping** [comment]
Hurrah! 😄 This is great!

**Comment by sdspikes** [comment]
Test status is currently at fail: 63, pass: 96

**Comment by sdspikes** [comment]
Now at 17 failures, 123 passing

**Review by zestyping — APPROVED** [review]
Yes!   This is great!

**Comment by zestyping** [comment]
I'm going to merge this in now—it's a huge improvement.  Could you continue on a new branch from dev?

**Pull request merged**
