### PR TITLE
Adjust text styles; fully scalable UI

### PR DESCRIPTION
**Pull request by zestyping**
This harmonizes the text sizes and styles throughout the app (with guidance from Nadav's designs).  The volume up/down buttons now scale the entire UI, and the app is usable on smaller screens.  It's even usable on a phone, especially when scaled down a step or two.

### CODE REVIEW

**Comment by zestyping** [comment]
Here's the UI on a phone (Xperia Z3 Compact, 720 x 1280), running at normal size:

buendia-phone-scale-normal

And one step down:

buendia-phone-scale-minus-one

**Comment by zestyping** [comment]
This is ready for approval and merging into dev.

**Comment by zestyping** [comment]
This also fixes some issues with the frozen headers, so it has more than just cosmetic value.

**Comment by llvasconcellos** [comment]
Comparing your printscreen with mine yours look different.
This is how it looks like on my Asus Zenfone 6 Lollypop with HD screen (1280x720) on the smaller font setting.
Still, great work!
screenshot_2015-10-06-08-19-56

**Comment by llvasconcellos** [comment]
Now I know why the difference. Some changes were missing from the dev branch. Now it's ok.

**Pull request merged**
