### PR TITLE
Display the text: "No patients" when a patient list is empty.

### LINKED ISSUE #183: Show no patients found
When you have 0 (zero) patients on one location show the message "No patients found." or something similar.

### PR DESCRIPTION
**Pull request by llvasconcellos**
This fixes #183

### CODE REVIEW

**Comment by dancunningham** [comment]
Just had a quick look at this, haven't tested. Some questions:
1. Does the swipe down to refresh still work with an empty patient list?
2. Does it behave correctly when you add the first patient?
3. What about if the first patient is added on another tablet?
4. Does it interact as expected with Search?

**Comment by llvasconcellos** [comment]
I'll test all this scenarios and get back to you.

**Comment by llvasconcellos** [comment]
@dancunningham It works fine on all 4 situations.

**Comment by capnfabs** [comment]
:+1: Good work, this looks great.

**Pull request merged**
