### PR TITLE
Feature/rafaelteixeira localize stringsxml to portuguese

### PR DESCRIPTION
**Pull request by TeixeiraRafael**
Hi this is the first version of the strings.xml translation to portuguese, it may need some revision.
Best regards,
Rafael.

### CODE REVIEW

**Comment by capnfabs** [comment]
Hey @TeixeiraRafael! Thanks for submitting this pull request :smile:

@G1DR4, any reason why you assigned @llvasconcellos? It would be good if you could take a look because you've done a translation in the past, and there's already a lot assigned to Leonardo.

**Comment by capnfabs** [comment]
Assigned to @G1DR4. Please review Rodrigo.

**Comment by llvasconcellos** [comment]
@TeixeiraRafael Hi Rafael. What tool did you use to translate the app? The pt file is in alphabetical order, which is different from the english and makes it more difficult to review.

**Comment by llvasconcellos** [comment]
@TeixeiraRafael Thanks for your contribution to the software! We really appreciate it.

**Comment by TeixeiraRafael** [comment]
@llvasconcellos Hi Leonardo, I used the translations editor on the AndroidStudio itsef, thanks for reviewing the pull request, it is a pleasure to contribute to this project!

**Comment by llvasconcellos** [comment]
@TeixeiraRafael Valeu!

**Comment by capnfabs** [comment]
@llvasconcellos thanks for reviewing this! @TeixeiraRafael thanks for the change :)

**Pull request merged**
