### PR TITLE
Fix order sync

### PR DESCRIPTION
**Pull request by zestyping**
Orders were not getting automatically synced at all, previously.

### CODE REVIEW

**Comment by viniciusboson** [comment]
theses changes look fine to me

**Comment by G1DR4** [comment]
ok to me too

**Comment by llvasconcellos** [comment]
I don't see any difference after merging this fix to dev and it seems that it still missing something.

I clicked in "ADD A NEW TREATMENT" and filled the form for a new medicine. After I saved a new encounter is created in the patient's visits tab on OpenMRS. But the location, provider and observation is missing as you can see bellow:

image

But when I add a new _order executed_ (mark as given now) then on OpenMRS is created another encounter but this time the location and observation is informed only missing the provider name. See bellow:

image

**Again, I don't see any difference with or without this fix.**

**Comment by llvasconcellos** [comment]
During my tests, at one point, all the "order executed" became zeroes again but in OpenMRS they were still there. You can see this on patient ID number 5.

**Comment by llvasconcellos** [comment]
@capnfabs Can you take a look at this?

**Comment by capnfabs** [comment]
The code looks 👌 to me; I think the issues you're observing [above](#issuecomment-148270559) are unrelated to this change specifically.

Can you clarify what the issue is @llvasconcellos? I'd be inclined to merge this (it's an improvement) and then address those issues separately.

**Pull request merged**
