### PR TITLE
Enable multidex to temporarily avert the dexocalypse.

### PR DESCRIPTION
**Pull request by capnfabs**
- Bump build tools version to latest. This is required for Multidex.
- Delete ic_launcher from OdkCollect, required because later versions of the AAPT build tool handle
  duplicate resources as errors, and this file was causing the build to fail.
- Add dependency upon the legacy HTTP library. API 23 deprecated Apache HTTP, but we're still using
  it for Health check code.
- Update OdkCollect to latest build tools as well, because it was separately including the legacy
  Apache HTTP library, which was resulting in conflicts from having the same JAR included twice.
  Updating to the latest build tools means that it can use the same legacy library as `:app`, which
  eliminates the conflict.
- Update support library versions to 23 so that they work with the latest build tools.
- Enable Multidex. Tested on API 21 (L) and 19 (KK)
- Remove Guava as a direct dependency, and delete code that used it from `JsonPatient`. Note that
  Guava is still included by Pebble as a transitive dependency, but I don't want developers on this
  project to be able to use it in code we control, so we have the flexibility to remove the
  dependency one day.

See https://slack-files.com/T02T5LNM4-F0JQ1UDRV-716ebe431f for details.

### CODE REVIEW

**Comment by llvasconcellos** [comment]
Looks good! 
Does this means that we now need Lollipop to run the client?

**Comment by llvasconcellos** [comment]
Great that you updated those libraries!

**Comment by llvasconcellos** [comment]
It builds and run without problems.

**Comment by llvasconcellos** [comment]
I was testing some other problem with this build and it seems that I cannot save a form with it.
It might be unrelated but I'll test it on another branch.

``` java
01-19 12:45:44.996  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ Error submitting form to server
    com.android.volley.ServerError
            at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:161)
            at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:110)
01-19 12:45:44.997  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ {"error":{"message":"Unable to convert object into response content","code":"org.openmrs.projectbuendia.webservices.rest.XformInstanceResource:134","detail":"org.openmrs.module.webservices.rest.web.response.ConversionException: Error processing xform data\n\tat org.openmrs.projectbuendia.webservices.rest.XformInstanceResource.createInner(XformInstanceResource.java:134)\n\tat org.openmrs.projectbuendia.webservices.rest.XformInstanceResource.create(XformInstanceResource.java:112)\n\tat org.openmrs.module.webservices.rest.web.v1_0.controller.MainResourceController.create(MainResourceController.java:86)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)\n\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.lang.reflect.Method.invoke(Method.java:606)\n\tat org.springframework.web.bind.annotation.support.HandlerMethodInvoker.invokeHandlerMethod(HandlerMethodInvoker.java:176)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.invokeHandlerMethod(AnnotationMethodHandlerAdapter.java:426)\n\tat org.springframework.web.servlet.mvc.annotation.AnnotationMethodHandlerAdapter.handle(AnnotationMethodHandlerAdapter.java:414)\n\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:790)\n\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:719)\n\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:644)\n\tat org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:560)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:755)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:848)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1506)\n\tat org.openmrs.module.web.filter.ForcePasswordChangeFilter.doFilter(ForcePasswordChangeFilter.java:61)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:72)\n\tat org.openmrs.module.xforms.web.XformsFilter.doFilter(XformsFilter.java:69)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.web.filter.GZIPFilter.doFilterInternal(GZIPFilter.java:64)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.webservices.rest.web.filter.AuthorizationFilter.doFilter(AuthorizationFilter.java:108)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:58)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.openmrs.module.web.filter.ModuleFilterChain.doFilter(ModuleFilterChain.java:70)\n\tat org.openmrs.module.web.filter.ModuleFilter.doFilter(ModuleFilter.java:54)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.web.filter.OpenmrsFilter.doFilterInternal(OpenmrsFilter.java:107)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.springframework.orm.hibernate3.support.OpenSessionInViewFilter.doFilterInternal(OpenSessionInViewFilter.java:198)\n\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)\n\tat org.openmrs.web.filter.StartupFilter.doFilter(StartupFilter.java:105)
01-19 12:45:44.997  20016-20016/org.projectbuendia.client.dev E/buendia/OdkActivityLaun﹕ Server error. Internal error stack trace:
```

**Comment by capnfabs** [comment]
No it still works on KitKat, I tested it :)

Updated the libraries because I had to to rev the build tools as well, but yeah, I'm glad I finally got to update them.

I think the problem you're referring to might have been introduced by https://github.com/projectbuendia/buendia/pull/59 ? I'd be surprised if it was this change, at least.

**Comment by llvasconcellos** [comment]
Yes, dev branch is also having this problem.

**Pull request merged**
