### PR TITLE
Wip

### PR DESCRIPTION
**Pull request by llvasconcellos**

### CODE REVIEW

**Comment by capnfabs** [comment]
What's going on with this PR?

**Comment by llvasconcellos** [comment]
@capnfabs I should have merged feature/rodrigo-void_observation into wip not the other way around. How can I fix this?

**Comment by llvasconcellos** [comment]
@capnfabs Sorry, this is a terrible lack of attention mistake. It won't happen again. I might have done this when rebasing void observations.

**Comment by capnfabs** [comment]
No worries, it happens :)

Ok, so here's what happened:
- `wip` got merged into `feature/rodrigo-void_observations` 
- `feature/rodrigo-void_observations` got merged into `dev`.

So, it's valuable to produce a list of commits that shouldn't have been in merged into `dev`, but got merged in via `wip --> feature/rodrigo-void_observations --> dev`.

Here's how to do that:
- The merge commit for `feature/rodrigo-void_observations --> dev` was c37570797e9d2aa68652a14164eb66fabef723af.
- The commit on `dev` prior to that was 711eaa271b5619cd0126fe07e6750096354a00bb.
- `git log 711eaa271b5619cd0126fe07e6750096354a00bb..projectbuendia/wip --no-merges` shows all commits that were on the `dev` branch before the merge from `feature/rodrigo-void_observations` that weren't on the `wip` branch.
- The results of that command are empty, which means everything that was in `wip` was also already in `dev`.

So it's all good, this had no effect on our `dev` branch.

**Comment by llvasconcellos** [comment]
Sight! Thanks.

**Pull request merged**
