### PR TITLE
Cleaning up OdkActivityLauncher class

### PR DESCRIPTION
**Pull request by viniciusboson**
I've cleaned up the `OdkActivityLauncher` class to be more readable and maintainable. 

There were many methods too long and they were doing to many things that it was necessary to debug them paying very close attention to understand what they were supposed to do.

Theses changes don't have any intention to cause side-effects. This is just a janitor PR which will be useful for future changes.

### CODE REVIEW

**Comment by capnfabs** [comment]
Awesome, thanks for doing this! That class really needed some work. I've left some comments on the individual commits but after that it's good to go :+1:

**Comment by capnfabs** [comment]
This is good to go when you're ready :+1:

**Comment by viniciusboson** [comment]
@capnfabs, thx for you opinion ...
I've chosen a try-catch approach just to centralize both event error handling and method exit point.
I've removed the validations methods too because their declaration + comments are longer than themselves ... 
I've pushed an prior commit with trigging the events each time too ...
What do you think about it ?

**Comment by capnfabs** [comment]
Hey @viniciusboson, nice work! I like the try/catch mechanism. Two notes:
- Just because the method declaration and comments are longer, doesn't mean it's not worth refactoring them out :) It's ok so long as the code is easier to understand, even if the actual file is longer.
- If it's important that the exceptions are caught or exceptions, throw checked exceptions rather than unchecked exceptions. `IllegalStateException` is an unchecked exception.

**Comment by viniciusboson** [comment]
Hey @capnfabs. I've done the changes that you suggested. I created a checked ValidationException class and rolled-back to keep validations inside each method.

**Comment by capnfabs** [comment]
Thanks Vinicius! This is good to go, feel free to merge when you're ready.

**Pull request merged**
