### PR TITLE
Changing require wifi default to true.

### LINKED ISSUE #149: Snackbar no longer picking up wi-fi status
It looks like Snackbar behaviour has changed. When I switch off wi-fi, it used to say “Wi-fi disconnected” with a “Connect” button. Now it goes straight to “Server unreachable” with a “More info” button. The message should depend on the detected situation.

### PR DESCRIPTION
**Pull request by llvasconcellos**
This fixes #149

### CODE REVIEW

**Comment by capnfabs** [comment]
Looks good to me.

FYI on Release builds (which we're not using at the moment) and debug builds built by jenkins, Wifi does default to true - what you're observing here only applies to local builds.

**Comment by dancunningham** [comment]
@capnfabs I just installed from the client-master build and "Require wifi connection" is not set to true.

**Comment by dancunningham** [comment]
Oh, maybe because I didn't erase data.

But not sure why I would ever have set that to false? Was false the default previously?

**Comment by llvasconcellos** [comment]
@dancunningham That option didn't exist before. The app required wifi as a default behavior.
After I talked to @zestyping he added this option and default it to false.
I don't know about jenkins build though.

**Comment by llvasconcellos** [comment]
We also could document the Require WIFI on the wiki.

**Comment by zestyping** [comment]
The original motivation for making it false by default in dev builds was
that we run dev builds in the emulator so often.  In the emulator there is
no wifi, so when "Require wifi connection" was true, the snackbar would
always be complaining about wifi, which prevented us from seeing or testing
any of the other snackbar messages reliably — for example, app updates were
inaccessible.

**Comment by capnfabs** [comment]
@dancunningham if the settings aren't found, the defaults are written on first boot. So even with this change, the old default setting would persist if you hadn't cleared data.

In my opinion, this isn't ideal and is probably something we should change.

**Comment by capnfabs** [comment]
I'm going to close this change - as stated above:

> Release builds (which we're not using at the moment) and debug builds built by jenkins, Wifi does default to true - what you're observing here only applies to local builds.

I think that's good enough.

**Pull request closed without merging**
